import productImage from '@/images/leadership.svg';
import mentalModel from '@/images/mentalModel.svg';
import wiframeImage from '@/images/wireFraming.svg';
import Avatar1 from '@/images/Avatar1.svg';
import Avatar2 from '@/images/Avatar2.svg';
import Avatar3 from '@/images/Avatar3.svg';

export const BLOGS_DATA = [
    {   id: 1,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 2,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 3,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
    {   id: 4,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 5,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 6,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
    {   id: 7,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 8,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 9,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
    {   id: 10,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 11,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 12,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
    {   id: 13,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 14,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 15,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
    {   id: 16,
        image: productImage,
        title: 'Management',
        heading: 'Bill Walsh leadership',
        text: 'Like to know the secrets of transforming a 2-14 team into',
        avatar: Avatar1,
        userName: 'Alec Whitten',
        date: '17 Jan 2022'
    },
    {   id: 17,
        image: mentalModel,
        title: 'Product',
        heading: 'PM mental models',
        text: 'Mental models are simple expressions of complex processe',
        avatar: Avatar2,
        userName: 'Demi WIlkinson',
        date: '16 Jan 2022'
    },
    {   id: 18,
        image: wiframeImage,
        title: 'Design',
        heading: 'What is Wireframing?',
        text: 'Introduction to Wireframing and its Principles. Learn from the best',
        avatar: Avatar3,
        userName: 'Candice Wu',
        date: '15 Jan 2022'
    },
]
