export const JOBS_DATA = [
  {
    id: 1,
    title: "Next.js Developer",
    description: "We are seeking a proficient Next.js Developer to become a part of our team. As a Next.js Developer, your role will involve overseeing the creation and upkeep of web applications using the Next.js framework. Your main emphasis will be on incorporating user interface elements and merging front-end and back-end services. Proficiency in JavaScript, React, and a comprehensive grasp of the Next.js framework are essential for this role.",
    position: "Frontend Developer",
    duration: "12 days ago",
    resonsibilities: [
    {res :  "Crafting user-facing features using Next.js and React.js "},
    {res :  " Creating reusable components and front-end libraries for future application    "},
    {res :  "Enhancing application speed and scalability      "},
    {res :  "Collaborating with the back-end development team to blend user-facing elements with server-side logic "},
    {res :  "Ensuring optimal application performance and addressing front-end related issues      "},
    {res :  "Keeping updated with emerging technologies and industry trends      "},
    ]
    , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  ,
  {
    id: 2,
    title: "MERN Stack Developer",
    description: "We are in search of a skilled and seasoned MERN Stack Developer to join our active team. As a member of our development team, you will play a crucial role in creating and upkeeping top-notch applications. Your main responsibility will involve handling all aspects of server-side logic, overseeing the central database, and ensuring optimal performance and swift response to front-end requests. Additionally, you will collaborate with your peers to seamlessly integrate front-end components into the application.",
    position: "Full Stack Developer",
    duration: "12 days ago",
    resonsibilities: [
    {res :  "Developing new user-facing features using React.js     "},
    {res :  "Building reusable components and front-end libraries for future use     "},
    {res :  "Translating designs and wireframes into high-quality code     "},
    {res :  "Optimizing components for maximum performance across a vast array of web-capable devices and browsers     "},
    {res :  "Building and maintaining efficient and reliable Node.js server-side applications     "},
    {res :  "Ensuring the best possible performance, quality, and responsiveness of the application     "},
    {res :  "Identifying and fixing bugs and performance bottlenecks     "},
    {res :  "Helping maintain code quality, organization, and automatization     "},
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  ,
  {
    id: 3,
    title: " Frontend Developer",
    description: "We are in search of a skilled and innovative Frontend Developer to join our team. As a Frontend Developer, you will be responsible for implementing visual elements that users see and interact with in a web application. Your primary focus will be on the development of user interfaces and ensuring the responsiveness of applications. You should have a strong understanding of web markup, including HTML5 and CSS3, as well as proficiency in client-side scripting and JavaScript frameworks, such as Angular, React, or Vue.js.",
    position: " Frontend Developer",
    duration: "12 days ago",
    resonsibilities: [
     {res : "Develop user interfaces for web applications using HTML, CSS, and JavaScript      "},
     {res : "Collaborate with the design team to translate UI/UX design wireframes into high-quality code      "},
     {res : "Optimize applications for maximum speed and scalability      "},
     {res : "Implement responsive designs to ensure compatibility across various devices and platforms      "},
     {res : "Stay updated on emerging technologies and industry trends in frontend development      "},
     {res : "Collaborate with the back-end developers and web designers to improve the usability of applications      "},
     {res : "Conduct testing and debugging to ensure the quality and performance of applications      "},
     {res : "Stay updated on security and data protection best practices      "},
   
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  ,
  {
    id: 4,
    title: "PHP Laravel Developer ",
    description: "We are looking for a skilled PHP Laravel Developer to join our team. As a PHP Laravel Developer, you will be responsible for developing and maintaining server-side web applications and ensuring high performance and responsiveness to requests from the front-end. Your primary focus will be the development of all server-side logic, definition, and maintenance of the central database, and ensuring high performance and responsiveness to requests from the front-end.",
    position: " Backend Developer",
    duration: "12 days ago",
    resonsibilities: [
    {res :  "Developing and maintaining server-side web applications using PHP Laravel     "},
    {res :  "Designing and implementing efficient, reusable, and reliable PHP code     "},
    {res :  "Integrating data storage solutions, including databases, key-value stores, blob stores, etc.     "},
    {res :  "Ensuring high performance and responsiveness of the server-side applications     "},
    {res :  "Implementing front-end elements into the application     "},
    {res :  "Collaborating with the front-end developers and other team members to establish objectives and design more functional, cohesive codes to enhance the user experience     "},
    {res :  "Identifying and fixing any technical problems and performance bottlenecks     "},
    {res :  "Helping maintain code quality, organization, and automatization     "},
   
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  ,
  {
    id: 5,
    title: "Blockchain Developer ",
    description: "We are seeking a knowledgeable and experienced Blockchain Developer to join our team. As a Blockchain Developer, you will be responsible for designing, implementing, and supporting a distributed blockchain-based network. Your primary focus will be on developing and maintaining blockchain protocols, designing and implementing smart contracts, and integrating them with distributed applications. You should have a strong understanding of blockchain technology and be well-versed in various blockchain platforms and programming languages.",
    position: "Blockchain Developer ",
    duration: "12 days ago",
    resonsibilities: [
     {res : "Designing and implementing blockchain solutions and smart contracts    "},
     {res : "Developing and maintaining blockchain protocols    "},
     {res : "Integrating blockchain functionalities into distributed applications    "},
     {res : "Collaborating with the team to identify and address any technical challenges or issues    "},
     {res : "Conducting research and staying updated on the latest blockchain technology trends and developments    "},
     {res : "Ensuring the security and integrity of the blockchain network    "},
     {res : "Participating in the planning and development of blockchain products and services    "},
   
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  ,
  {
    id: 6,
    title: "Node.js Intern ",
    description: "We are looking for a motivated and enthusiastic Node.js Intern to join our team. As a Node.js Intern, you will have the opportunity to learn and contribute to the development of various web applications and services. Your primary focus will be on gaining practical experience in developing and maintaining server-side applications using Node.js. This internship will provide you with hands-on experience in a professional environment and the opportunity to work closely with our experienced development team.",
    position: "Intern ",
    duration: "12 days ago",
    resonsibilities: [
     {res : "Assisting in the development and maintenance of server-side applications using Node.js     "},
     {res : "Collaborating with the team to contribute to the design and implementation of various projects     "},
     {res : "Participating in code reviews and debugging sessions     "},
     {res : "Learning and applying best practices and standards in software development     "},
     {res : "Assisting in the optimization of applications for maximum speed and scalability     "},
     {res : "Contributing to the documentation of codes and processes     "},
     {res : "Keeping up to date with emerging technologies and industry trends in Node.js development     "},
   
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  {
    id: 7,
    title: "Python Developer",
    description: "We are seeking a skilled and motivated Python Developer to join our team. As a Python Developer, you will be responsible for developing and maintaining high-quality Python applications. Your primary focus will be on writing reusable, testable, and efficient code, as well as implementing and integrating data storage solutions. You should have a strong understanding of Python and its core principles, as well as familiarity with some of the following technologies: Django, Flask, or other Python frameworks.",
    position: "Python Developer",
    duration: "12 days ago",
    resonsibilities: [
     {res : "Writing and implementing efficient, reusable, and reliable Python code     "},
     {res : "Designing and implementing low-latency, high-availability, and performant applications     "},
     {res : "Integrating user-facing elements developed by front-end developers with server-side logic     "},
     {res : "Implementing data storage solutions and databases     "},
     {res : "Optimizing applications for maximum speed and scalability     "},
     {res : "Implementing security and data protection measures     "},
     {res : "Participating in the entire application lifecycle, focusing on coding and debugging     "},
     {res : "Collaborating with the team to define and design new features    "},
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  {
    id: 8,
    title: "Shopify Backend Developer ",
    description:"We are looking for a skilled and dedicated Shopify Backend Developer to join our team. As a Shopify Backend Developer, you will be responsible for developing and maintaining the backend infrastructure of our Shopify e-commerce platform. Your primary focus will be on implementing custom features, optimizing the platform for performance, and ensuring the seamless integration of third-party applications. You should have a strong understanding of Shopify's APIs and backend development best practices.",
    position: "Senior",
    duration: "12 days ago",
    resonsibilities: [
      {res : "Developing and maintaining the backend infrastructure of our Shopify e-commerce platform     "},
      {res :  "Implementing custom features and functionalities using Shopify's APIs and backend technologies     "},
      {res :  "Optimizing the platform for performance and scalability     "},
      {res : "Integrating third-party applications and services to enhance the platform's capabilities     "},
      {res :  "Collaborating with the front-end development team to ensure the seamless integration of design and functionality     "},
      {res :  "Conducting regular testing and debugging to ensure the stability and reliability of the platform     "},
      {res :  "Providing technical guidance and support to team members and stakeholders     "},
      {res :   "Staying updated on the latest Shopify updates and best practices in e-commerce development     "},
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  {
    id: 9,
    title: "SQA Engineer",
    description:"(SQA) Engineer to join our team. As an SQA Engineer, you will be responsible for ensuring the quality and reliability of our software products and applications. Your primary focus will be on designing and implementing test plans, identifying and documenting technical issues, and collaborating with the development and product teams to enhance product quality. You should have a strong understanding of software quality assurance methodologies, tools, and processes.",
    position: "Senior",
    duration: "12 days ago",
    resonsibilities: [
      {res :  "Design, develop, and execute comprehensive test plans and test cases to ensure software quality      "},
      {res : "Identify, record, and thoroughly document technical issues and bugs      "},
      {res : "Collaborate closely with the development and product teams to troubleshoot and resolve issues      "},
      {res : "Perform thorough validation and verification testing to ensure the highest level of product performance      "},
      {res :  "Conduct regular regression testing to ensure the stability of software applications      "},
      {res :  "Provide timely and accurate reports on quality assurance and testing activities      "},
      {res :  "Participate in the continual improvement of SQA processes and methodologies      "},
      {res : "Communicate and coordinate with cross-functional teams to ensure the highest standards of quality are met      "},
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  {
    id: 10,
    title: "Web Developer",
    description:"Web Developer, you will be responsible for designing, coding, and modifying websites, from layout to function and according to our company's specifications. Your primary focus will be on creating visually appealing sites that feature user-friendly design and clear navigation. You should have a strong understanding of web markup languages, as well as experience with client-side scripting and JavaScript frameworks.",
    position: "Senior",
    duration: "12 days ago",
    resonsibilities: [
      {res :"Designing and developing websites according to company specifications  "},
      {res : "Creating visually appealing site layouts and user interfaces      "},
      {res :"Building websites using technologies such as HTML, CSS, and JavaScript      "},
      {res : "Ensuring cross-platform compatibility and responsiveness for seamless user experience      "},
      {res :"Optimizing websites for maximum speed and scalability      "},
      {res : "Collaborating with the design team to ensure the technical feasibility of UI/UX designs      "},
      {res :"Integrating data from various back-end services and databases      "},
      {res :"Conducting website testing and resolving any issues or bugs      "},
    ]   , benefits : [
      { ben : 'Flexible Timing'},
      { ben : 'Refreshment Activities'},
      { ben : 'Feul Allownece'},
      { ben : 'Gym Allownece'},
      { ben : 'Car Allownece'},
      { ben : 'Paid Leaves'},
      { ben : 'Monthly Dinner'},
      { ben : 'Annual Trips'},
      { ben : 'Performance Bonuses'},
    ]
  },
  
];
